FROM scratch AS ctx

COPY lib /lib
COPY sysext /sysext


FROM ghcr.io/b-koch/hestia:latest AS builder

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/sysext/build_sysext.sh


FROM scratch

COPY --from=builder /out/sysext.raw /sysext.raw
